title: Trust Madade 
description: A portfolio showcasing projects in data analytics, marketing strategy, and visualization.
author: Trust Madade
url: "https://trustmadade.github.io"
baseurl: "" # do not include a trailing slash

# SEO and metadata
keywords: "Marketing Analytics, Data Visualization, SQL, Power BI, Tableau, Python, Business Intelligence"

# Theme and layout
theme: minima
markdown: kramdown
permalink: pretty
timezone: America/Los_Angeles

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Navigation links
nav_links:
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Resume"
    url: "/resume/"
  - title: "Contact"
    url: "/contact/"
